### ISSUE TITLE
Remove /twitchemotes/set/:setID endpoint

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/api#332]
Chatterino no longer makes use of the `/twitchemotes/set/:setID` endpoint provided by this API. Could this be removed? 

@pajlada you might have metrics on external callers. I doubt anyone else is using it but would suck to drop it with 0 notice ![image](https://user-images.githubusercontent.com/4962764/176995569-a2180f24-e79b-47c4-8d5b-5d78cb793a31.png)

**Comment by pajlada** [comment]
I don't have metrics, once we have metrics I would be more comfortable deprecating endpoints

**Comment by pajlada** [comment]
I can confirm that there have been no requests to the `/twitchemotes/set/:setID` endpoint since we started tracking this, other than the requests I made just now to make sure it was being tracked

![image](https://user-images.githubusercontent.com/962989/229784732-64ed8d3f-e2fb-4a74-a761-da0428093698.png)

![image](https://user-images.githubusercontent.com/962989/229784820-7c185ac7-daed-4045-8df9-2e642c75da4f.png)
