### ISSUE TITLE
Allow hosters to blocklist domains

### ISSUE THREAD

**Issue by pajlada** [Chatterino/api#391]
Make it easier to opt out of certain websites.

Open questions:
Should this blocklist be maintained in a database or in a config file/environment variable?
Should the blocklist be per domain? a complete url as a regex so we can block certain parts of websites only?

**Comment by leon-richardt** [comment]
Can we assume that hosters don't want to be fetched from _any_ Chatterino API instance (including self-hosted ones)? If so, we should presumably provide a way to propagate opt-out requests submitted to one instance (or maybe only to the "main" instance?) to other instances.

**Comment by KararTY** [comment]
> Can we assume that hosters that don't want to be fetched want to opt out from _any_ Chatterino API instance (including self-hosted ones)?

I'm pretty sure if a website doesn't want chatterino-api to crawl it, they can just block its user-agent. I think this issue is related to having "hosters" ***(as in self-hosters of Chatterino-API)*** disable or blocklist some domains.

Full regex sounds more useful, sometimes you really just want to block a very specific Twitter user but not all of Twitter. I assume this would aid in that.

**Comment by pajlada** [comment]
> Can we assume that hosters that don't want to be fetched want to opt out from _any_ Chatterino API instance (including self-hosted ones)?
> 
> If so, we should presumably provide a way to propagate opt-out requests submitted to one instance (or maybe only to the "main" instance?) to other instances.

That's fair - probably something coded into the source code itself then



> I'm pretty sure if a website doesn't want chatterino-api to crawl it, they can just block its user-agent. I think this issue is related to having "hosters" _**(as in self-hosters of Chatterino-API)**_ disable or blocklist some domains.

This is not feasible for every hoster, and it might not be enough either if the requests themselves are already too much.

**Comment by leon-richardt** [comment]
For completeness, there is a authentication problem looming here if we plan to automate propagation of opt-out requests across instances. We must make sure that opt-out requests are submitted by an authorized party, i.e., we must authenticate that the submitter is also the actual operator of the domain. Otherwise, we will be an easy target for malicious actors that wish to disturb the service.
I believe this also forces us to only allow propagation of opt-out requests **from the main instance to other instances**.

The easiest way to authenticate could be manual review by a trusted party and authentication on a case-by-case basis. More sophisticated solutions might implement something like the ACME challenge-response procedure, but this will likely involve significant development effort to get right.

Anyway, it's a more complex problem than I initially thought.

**Comment by Mm2PL** [comment]
I think you are overcomplicating this, we should just use a header which says "stop crawling my website". And we cache this for a decent time. Maybe write to disk.

8 gru 2022 00:34:08 Leon Richardt ***@***.***>:

**Comment by KararTY** [comment]
This. Even if one want to complicate it slightly to add more customizability, potentially hipsters can add .chatterino.ignore file to their root and have a bunch of gitignore-like rules. :tf: (Can't do actual regex or potential for reDoS) Chatterino reads that and caches it and then decides whether to crawl or not. No fancy propagation needed. 
    Den torsdag 8 december 2022 10:10:02 CET, Mm2PL ***@***.***> skrev:  
 
 

I think you are overcomplicating this, we should just use a header which says "stop crawling my website". And we cache this for a decent time. Maybe write to disk.

8 gru 2022 00:34:08 Leon Richardt ***@***.***>:

**Comment by leon-richardt** [comment]
> I think you are overcomplicating this

Maybe I am.

> we should just use a header which says "stop crawling my website"

I don't think this is feasible to implement for every hoster (also see pajlada's comment earlier).

**Comment by kornes** [comment]
checking of robots.txt could be added too, 
also many web crawlers add own website/github url to useragent, it could link to brief description and optout options.

**Comment by pajlada** [comment]
We've chatted about checking robots.txt but it hasn't felt appropriate to us as we don't crawl as much as we extract data on a single page.

Adding information in the UserAgent seems appropriate once we've decided on a method.

My thinking is making a simple solution before we go for something super advanced, but I want this to be something we can help with, not only something where we require the user to change something on their end to kick us out.
