### ISSUE TITLE
Make cache timeout values configurable

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/api#410]
Idea spawned from https://github.com/Chatterino/api/pull/409#issuecomment-1378603767

**Comment by M4tthewDE** [comment]
I took a look at how to implement this the best way. Since there re a good amount of different caches (>10), individual config entries for each timeout value would bloat the config quiet a bit. 

A possible solution is to use a map:
```
cache-timeouts:
   youtube: 24h
   twitter: 10m
```

This is nice in the `config.yml` in my opinion, but as far as I can see viper does not support maps in command-line flags.
The cache value could as a result only be set via the `config.yml`.

Not sure which of the two would be the best option, suggestions appreciated!

**Comment by pajlada** [comment]
We already don't use maps where we could, so I think it makes sense to just add long keys here too
atm we have `youtube-api-key`, we'd want to add something like `youtube-video-cache-duration` and `youtube-profile-cache-duration`, for twitter we'd add `twitter-profile-cache-duration` and `twitter-tweet-cache-duration`.

I'm flexible with the naming
